mottosso/Qt.py

.gitignore
README.md
setup.py

Also made version semver compatible, and uploaded to PyPI.

Updated README.md

---

Qt.py

Fixes https://github.com/mottosso/Qt/issues/7

Removed prints

---

Qt.py

Here's an alternative to #10 and #9.

Cosmetics and #10

---

Qt.py
README.md
setup.py

Not sure about PySide2 here, are you able to test, @fredrikaverpil?

Implement #21

---

Qt.py

Revert "Provide Qt.load_ui"

---

.travis.yml
Qt.py
tests.py

Keeping this open for subsequent commits while I stretch the legs of Travis.
(Follow-up to #38 where I got lost in git)

Add support for Travis CI

---

README.md

Totally forgot I made this for you @fredrikaverpil.

Add developer guide

---

README.md

Revert "Added similar projects, fix #47"

---

.travis.yml

Travis with Ubuntu 14.04

---

README.md

Added similar projects

---

Qt.py
README.md
tests.py

Here's a version of scenario B from #51.

Enforce coexistence

---

.travis.yml

Now whenever we make a [release](https://github.com/mottosso/Qt.py/releases/new), Travis will automatically upload to PyPI.
Implements #32

Add automatic upload to PyPI on new release

---

tests.py

Remove test_sip_api_pyqt4

---

tests.py

Sorry if this comes around as a little silly, but I like to keep things tidy 😉

Remove whitespace on blank lines

---

Qt.py

- Fix https://github.com/mottosso/Qt.py/issues/68
- Version bump to 0.3.2
Do we add tests for remaps?

Add remap for QItemSelection and QItemSelectionModel

---

README.md

Add who's using Qt.py

---

README.md

These should be in the README I think. :)

Add external guides to README

---

CAVEATS.md
appveyor.yml
build_caveats_tests.py
caveats.py
tests.py

AppVeyor support

---

README.md

Enhance load_ui documentation

---

appveyor.yml

So that other PRs won't fail because of that.

Retry Appveyor/PyQt4 download

---

README.md

Publicity and additional project

---

Qt.py

Changes.
- [Support QtWebKitWidgets](https://github.com/mottosso/Qt.py/commit/b63a737662576ffa0b176f5e24047e07e92f0e76)
- [Repair PySide support](https://github.com/mottosso/Qt.py/commit/a84dbfd49ab84546560e2228197c4f5c499470db)
PySide wasn't working under some circumstances, see [stack trace](https://travis-ci.org/mottosso/Qt.py/jobs/149452858) on Travis.

Version bump

---

README.md
tests.py

Some clarification, but also the idea to put argument signatures in the documentation, similar to how it would appear on ReadTheDocs and Sphinx-generated documentation in general.
Let me know what you think!

Update documentation for load_ui

---

.travis.yml
CAVEATS.md
Dockerfile-py2.7
Dockerfile-py3.5
build_membership.py
run_tests.py
tests.py

#122
Without access to Docker at the moment, will trust Travis to run tests for me.

Implement #122

---

Qt.py
tests.py

Fix QtCompat attributes

---

Qt.py

Universal wheel: Bump dev version

---

Qt.py

Implements universal wheel after next release/tagging.
Fix: #162
Previous PRs leading up to this PR: #163 #166 #167

Bump version for universal wheel

---

README.md

It is not a company.
But it is a tools pack for CG too.
Main tool is Afanasy - free and open-source render farm manager.

CGRU project added (http://cgru.info/)

---

README.md

And thank you for your amazing tool :+1:

README: add Mikros Image

---

README.md

We integrated Qt.py a month ago in version 1.5.1 . Thanks for all this work.

Add Syncplay to the "Projects using Qt.py" section

---

Qt.py
README.md

Let's assemble what should be written in the release notes for 1.1.0.

Release 1.1.0

---

README.md

Fix wrong date of release

---

README.md

I just added our studio and the BlenderUpdater project to the Readme

added Overmind Studios + BlenderUpdater

---

README.md

We've been using Qt.py extensively (and exclusively for all Qt work) for the last year, so just adding to the list of studios using Qt.py.

Update README.md to include Spin VFX

---

README.md

Adding QtPyConvert as a "project using Qt.py"

Adding QtPyConvert as a project that uses Qt.py

---

README.md

README: Add Futureworks to studios list using this module.

---

README.md

See https://github.com/mottosso/Qt.py/issues/310

README: add python_qt_bindings

---

Qt.py

This implements https://github.com/mottosso/Qt.py/pull/258, which was out of date.

Add QStyleOptionViewItem to QtCompat

---

Qt.py

fix ui file using custom widget bug
https://github.com/mottosso/Qt.py/issues/344

fix bug #344

---

Qt.py

Add `QSound` to `_misplaced_members` dictionary.

Attempt to support QSound

---

README.md

Using Qt for internal projects.

GermanTechJobs - user

---

Qt.py
tests.py

This updates the convert function to work with files generated by pyside2-uic version 5.15.2

convert function handle files generated using uic 5.15.2
