- Qt.py
This makes it possible to `import Qt` straight from Qt.py:
```
~/code/Qt
❯ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Qt import QtWidgets
>>> print QtWidgets
<module 'PyQt5.QtWidgets' from '/usr/local/lib/python2.7/site-packages/PyQt5/QtWidgets.so'>
```
Please note: PR now targets the `master` branch.
> add loading of bindings

- Qt.py
```bash
$ set QT_PREFERRED_BINDING=PySide
$ python -c "from Qt import __binding__;print(__binding__)"
PySide
$ set QT_PREFERRED_BINDING=PyQt4
$ python -c "from Qt import __binding__;print(__binding__)"
PyQt4
$ set QT_PREFERRED_BINDING=NotExists
$ python -c "from Qt import __binding__;print(__binding__)"
ImportError: Preferred Qt binding "NotExists" not available
```
> Implement #22

- Qt.py
- README.md
- setup.py
Shouldn't use `__version__`, because it might be confused with the `__version__` of the binding.
```bash
$ python -c "import Qt;print(Qt);print(Qt.__version__)"
<module 'PySide' from 'C:\Python27\lib\site-packages\PySide\__init__.pyc'>
1.2.4
```
> Add __wrapper_version__

- Qt.py
Fix https://github.com/mottosso/Qt.py/issues/24
from Qt import load_ui
- The `load_ui` function is made-up and doesn't exist directly under either PyQt or PySide.
- I was unable to "alias" `QtUiTools.QUiLoader().load` directly, which is why I had to create a function.
Example usage in [this gist](https://gist.github.com/fredrikaverpil/2bcd40900a44ae0a89dbc60980804fdf). You can run the code from the gist in a shell or in Maya. I'm adding Nuke support into the gist now too...
`Qt.load_ui` becomes really useful, actually. I initially thought this wouldn't be the case. I'm going to rewrite a lot of our in-house code to support this for easier maintainability between Maya, Nuke, standalone and PySide, PyQt4, PySide2, PyQt5. The Qt.py module has surpassed my expectations already! 😄 
Version …
> Provide Qt.load_ui

- Qt.py
- README.md
Fix https://github.com/mottosso/Qt.py/issues/24
from Qt import load_ui
- The `load_ui` function is made-up and doesn't exist directly under either PyQt or PySide.
- I was unable to "alias" `QtUiTools.QUiLoader().load` directly, which is why I had to create a function.
Example usage in [this gist](https://gist.github.com/fredrikaverpil/2bcd40900a44ae0a89dbc60980804fdf). You can run the code from the gist in a shell or in Maya. I'm adding Nuke support too.
`Qt.load_ui` becomes really useful, actually. I initially thought this wouldn't be the case. I'm going to rewrite a lot of our in-house code to support this for easier maintainability between Maya, Nuke, standalone and PySide, PyQt4, PySide2, PyQt5. The Qt.py module has surpassed my expectations already! 😄 
Version bump to 0.2.5 included …
> Provide Qt.load_ui (retry)

- README.md
I've created an example/boilerplate script which loads .ui files into a window. Figured it could be nice to link to it, as it relies on `Qt.py`.
You can run it in a number of ways, as can be seen in the [README](https://github.com/fredrikaverpil/pyvfx-boilerplate/blob/master/README.md).
> Added link to pyvfx-boilerplate

- Qt.py
- README.md
- tests.py
Fix #37
@justinfx @mottosso Let's discuss this.
I get this when the API was already set to v2:
```python
python
>>> import Qt
Qt Warning: API 'QString' has already been set to version 1
Qt Warning: API 'QVariant' has already been set to version 1
```
> sip API v2

- .travis.yml
- Dockerfile
- tests.py
Run all tests isolated from each other.
If we wish to only see some tests run in its own subprocess, we could implement that at a later time.
Fix #56
This made it possible to also test PyQt4 for sip API v1.
> Implement nosepipe

- Qt.py
- tests.py
This merge request fixes #66 by also setting the imported bindings module to the path of the original `__name__`, and not just "Qt"
> Fixes #66 - Also copy binding module to __name__ in sys.modules

- CAVEATS.md
- README.md
Here's a starting point for conversation regarding https://github.com/mottosso/Qt.py/issues/65 ...
- I didn't call the file `INCOMPATIBILITIES.md` because of the long file name.
- I first added the TOC in the `README.md` but realised users may expect a TOC inside of `CAVEATS.md` and I really didn't want it in both of them for maintenance purposes.
> Add CAVEATS.md

- CAVEATS.md
- Dockerfile-py2.7
- Dockerfile-py3.5
- README.md
- tests.py
> Implement #109

- CONTRIBUTING.md
- README.md
> Readme refactoring

- Qt.py
this should be fixing #115 
please have a look and let me know.
> add missing remap

- Qt.py
I found that this was missing from `_pyqt4`:
PyQt4.QtCore.QStringListModel = PyQt4.QtGui.QStringListModel
This is already in `_pyside`:
PySide.QtCore.QStringListModel = PySide.QtGui.QStringListModel
> Add map for QStringListModel

- Qt.py
- README.md
Here's an idea for #111
Rather then post-checking that a binding has not been broken, we can pre-check by making sure nothing happening in Qt.py overwrites or alters any existing member.
With this, Qt.py can have no adverse effects on an original binding, other than affect other third-parties from adding members to where we also add them. Should we bother with that? Can we?
Notice the `add` and `remap` functions.
These replace the current layout of remapping and adding.
```python
PyQt4.QtWidgets = PyQt4.QtGui
remap(PyQt4, "QtWidgets", PyQt4.QtGui)
```
By using a function as opposed to directly assigning, we lose out on readability, but gain security.
The `safe=True` argument is meant to facilitate times where we *do* overwrite, but ensure to include a full array of tests to ensure the …
> Implement #111

- Dockerfile-py2.7
- Dockerfile-py3.5
- Qt.py
- README.md
- tests.py
Allright folks, let's get this started!
This command converts a PySide2-compiled .ui file into a Qt.py-compatible equivalent.
```bash
$ pyside2-uic my_ui.ui -o my_ui.py
$ python -m Qt --convert my_ui.py
$ cat my_ui_.py
```
Tested on [this file](https://gist.github.com/salvaom/afe312982140c926c21005d822c0f116#file-widget_designer1_uic2-py).
Also includes a non command-line version.
```python
>>> import Qt
>>> Qt.convert(lines="""\
from PySide2 import QtCore, QtGui, QtWidgets
class Ui_uic(object):
def setupUi(self, uic):
self.retranslateUi(uic)
def retranslateUi(self, uic):
self.pushButton_2.setText(
QtWidgets.QApplication.translate("uic", "NOT Ok", None, -1))
""".split("\n")
```
1. Run this on your GUIs, see that it works 
2. Where it doesn't work, help me narrow down the exact line that …
> Implement #131

- Dockerfile-py2.7
- Dockerfile-py3.5
- tests.py
Fix https://github.com/mottosso/Qt.py/issues/141
> Add pyside2-uic (executable) and pyside2uic (module)

- CAVEATS.md
- Qt.py
- README.md
- tests.py
This introduces a radical change to counter #139, #109, #112 and #96.
The change involves moving all added members of Qt.py to it's own individual module, `QtShim`.
```python
import Qt
Qt.setSectionResizeMode()
Qt.__binding__
from Qt import QtShim
QtShim.setSectionResizeMode()
QtShim.__binding__ == "PyQt5"
```
- See [Example](https://github.com/abstractfactory/Qt.py/blob/master/CAVEATS.md#workaround-1)
It also counteracts our current Achilles heel, which is that at some point one of our additions are bound to conflict with native existing members of the binding. For example, if one day PySide decides to add `__qt_version__` to their offering, but have a different type for it, like `tuple`, whereas we have `str`
So I'm on the fence about whether this is the right way to do it. The …
> Implement #139

- Qt.py
Before this commit, to fully comply with the license, one would need both the Qt.py and LICENSE files. This eliminates the latter dependency.
Thanks @erictrocks!
> Integrate license with Qt.py file

- Qt.py
Continuing attending #162 #163.
According to PEP440, this is the naming convention for a [developmental release](https://www.python.org/dev/peps/pep-0440/#developmental-releases), which we didn't follow in the previous attempt to upload a dev release to PyPi.
> X.Y.devN    # Developmental release
>
> X.YaN.devM       # Developmental release of an alpha release
> X.YbN.devM       # Developmental release of a beta release
> X.YrcN.devM      # Developmental release of a release candidate
> X.Y.postN.devM   # Developmental release of a post-release
> Universal wheel: attempt abide PEP440

- Qt.py
Hello
We are trying to unify our Qt UI tools to Qt.py.
It seems testing of QT_TESTING in _remap() function always returns True as it is tested against None but the bool() call converts None to False.
Here is my simple fixing.
If possible, could you specify more explicitly the expected or valid values for QT_VERBOSE, QT_TESTING, like on/off or 0/1? I think this would make things clearer.
Thanks,
Sol Kim.
> fix QT_TESTING test 

- CAVEATS.md
- Qt.py
- README.md
- build_membership.py
- examples/load_ui/baseinstance1.py
- examples/load_ui/baseinstance2.py
- setup.py
- tests.py
Hi all,
This is a first pass on #152, a strict enforcement of the PySide2 API.
It's a suggestion, so do not merge unless we've talked it through and are all happy with it.
Things to note:
1. Qt.py is now **twice as large** (from 446 to 889 lines) as before, due to explicitly specifying each member.
1. This *will* break existing code that uses members other than those found in PySide2.
1. A number of inconsistencies were immediately found (and fixed) in tests, CAVEATS and examples. This is a good thing! Have a look.
1. QtWebKit was excluded as it is not guaranteed to exist in PyQt4 and 5 (it's an optional add-on).
On (1), this isn't necessarily a disadvantage; it does make the code trivially simple and require close-to-zero understanding of the overall code to make contributions. Such as …
> Implement #152

- .travis.yml
See the URL below for docs on where travis expects to find "distributions":
https://docs.travis-ci.com/user/deployment/pypi/#Uploading-different-distributions
See issue #162
> Move "distributions" out of "on" part of "deploy"

- Qt.py
- README.md
- build_docker.sh
- build_membership.py
- run_docker.sh
- test_docker.sh
- tests.py
This implements #185, a loosening of the strictness in such a way that (1) still only PySide2 members are present, but (2) members are not required.
This should enable use in less than ideal environments, such as certain OSs that lack various submodules or submodule members, such as QtOpenGL, or applications that may or may not expose the entirety of a binding, such as the lack of QtHelp under Houdini.
The result should be software that is robust and reliable, with a Qt.py that is more forgiving where needed.
**To test**
```bash
$ pip install git+https://github.com/abstractfactory/Qt.py.git@implement185
$ python -c "import Qt"
$ git clone https://github.com/abstractfactory/Qt.py.git
$ cd Qt
$ git checkout implement185
$ python -c "import Qt"
```
Or copy/paste [this …
> Implement #185

- Qt.py
- tests.py
This makes the naming convention across original and added members uniform.
- #179
```python
from Qt import QtCompat
QtCompat.load_ui(...)
QtCompat.loadUi(...)
```
The convention is this:
1. mixedCase across the board
2. snake_case for dunder names
As dunder names are unique to Python, they remain [aligned with PEP8](https://www.python.org/dev/peps/pep-0008/#id35), though it's open for discussion whether these should be dunder names at all. E.g. `__binding_version__` could instead be `bindingVersion`.
Thoughts?
> Implement #179

- Qt.py
Thank you for develop and maintain Qt.py.
My script raises exception on Maya2015 (PySide).
`
from Qt import QtCore
QtCore.QItemSelectionRange(index)
`
But does not raise exception on Maya2017.
I can't check other Qt binding libraries. sorry.
I hope this PR will be helpful.
> pyside needs QItemSlectionRange

- Qt.py
Thank you for maintaining.
Not found QtCore.QItemSelectionRange on Maya 2017(PySide2) on Windows.
I Add QitemSelectionRange to PySide2 block.
Similar to this PR.
https://github.com/mottosso/Qt.py/pull/191
> PySide2 also needs QItemSelectionRange.

- Qt.py
- README.md
- tests.py
During the porting of legacy code to Qt.py the changing of API versions
causes issues. By optionally preserving it, we can control that behavior.
This is primarily an issue when porting legacy code to use Qt where we are in an environment where importing Qt in bootstraps could cause issues when it changed the api.
https://github.com/mottosso/Qt.py/issues/188
> Added QT_PRESERVE_API to prevent changing of API versions

- Qt.py
- tests.py
Hi there,
A small code contribution to handle an issue we faced when converting a compiled .ui file from PySide2 to Qt.py when _QtWidgets.QApplication.translate_ is called.
Considering this code:
```python
from PySide2 import QtCore, QtGui, QtWidgets
dialog.setWindowTitle(QtWidgets.QApplication.translate("MyDialog", "MY DIALOG", None, -1))
```
Before this fix, it becomes:
```python
from Qt import QtCore, QtGui, QtWidgets
dialog.setWindowTitle(Qt.QtCompat.translate("MyDialog", "MY DIALOG", None, -1))
```
After this fix, it becomes:
```python
from Qt import QtCompat, QtCore, QtGui, QtWidgets
dialog.setWindowTitle(QtCompat.translate("MyDialog", "MY DIALOG", None, -1))
```
> _convert: fix conversion of compiled .ui to Qt.py when QtCompat.translate is called

- Qt.py
- tests.py
This adds flags to `Qt.py` that allow end users to check the binding more easily.
Rather  than comparing strings in every piece of code like so:
```python
if Qt.__binding__ == 'PySide2': doSomething()
```
They can now simply do
```python
if Qt.PYSIDE2: doSomething()
```
This in turn makes for less error prone code since string comparisons have the increased risks of typos not caught till runtime.
> Binding State Enums

- Qt.py
This is a PR that aims to solve #211.
You can see in my first commit that I had been silently ignoring the missing modules, or setting dummy ones. Let me know if that is desired functionality, I doubt it is though.
> Binding specific replacement mappings as a dictionary, similar to _common_members.

- CAVEATS.md
- Dockerfile-py2.7
- Dockerfile-py3.5
- Qt.py
- README.md
- caveats.py
- tests.py
This adds a wrapper for `wrapInstance` and `getCppPointer` from `shiboken2` and automatically unifies the differences with `shiboken` and `sip` for both Python 2 and 3.
| Attribute               | Returns    
|:------------------------|:-----------
| `QtCompat.wrapInstance(addr=long, type=QObject)` | `QObject` |
`QtCompat.getCppPointer(object=QObject)`    | `long`    
- See #53 for details.
- To **test**, copy/paste [this file](https://raw.githubusercontent.com/abstractfactory/Qt.py/implement59/Qt.py)
**Usage**
```python
import sys
from Qt import QtCompat, QtWidgets
app = QtWidgets.QApplication(sys.argv)
button = QtWidgets.QPushButton("Hello world")
pointer = QtCompat.getCppPointer(button)
widget = QtCompat.wrapInstance(long(pointer), QtWidgets.QWidget)
assert widget == button
app.exit() …
```
> Implement wrapInstance and getCppPointer (#59)

- CAVEATS.md
- Qt.py
- README.md
- examples/QtSiteConfig/QtSiteConfig.py
- examples/QtSiteConfig/README.md
- examples/QtSiteConfig/main.py
- tests.py
#151 
I've added a framework for adding a class namespace for QtCompat functions. This allows gives you a clear indication of what type of QObject you should be calling this function on.
These objects should have a unique name so they don't conflict with real Qt objects, but the name should make it easy to identify what type QObject they are intended to work on. Currently I'm adding a t after the Q so `QFileDialog` becomes `QtFileDialog`, and `QHeaderView` becomes `QtHeaderView`. Some other ideas I have are 'QFileDialogCompat', 'QFileDialogC', 'CFileDialog', 'CompatQFileDialog', but I'm open to any suggestions.
I am using type to create the classes dynamically. For example this is how I'm creating the PySide implementation of the QtHeaderView class. It has 4 methods.
```python
attrs = …
```
> QtCompat namespacing

- CAVEATS.md
- Qt.py
- README.md
- examples/QtSiteConfig/QtSiteConfig.py
- examples/QtSiteConfig/README.md
- examples/QtSiteConfig/main.py
- tests.py
I noticed that this breaks backwards compatibility with `QtSiteConfig` and that there are no signs of compatibility not breaking again once we continue to add members to it.
- [Before](https://github.com/mottosso/Qt.py/blob/52e3c073c1baeef2c871a6e546a93458e84590a8/Qt.py#L611)
`QtSiteConfig.update_members(_common_members)`
- [After](https://github.com/mottosso/Qt.py/blob/2196efcaa9f8a13dab55d38433b4f14f7da6d957/Qt.py#L748)
`QtSiteConfig.update_members(_common_members, 'common')`
In practice, anyone who has used `QtSiteConfig` for anything will have their code broken. That's no good, the last thing I want is for users to fear updating their Qt.py release and for that we must maintain *complete* backwards compatibility until a new major release (i.e. 2.0) is made.
@MHendricks I'd suggest we …
> Revert "QtCompat namespacing"

- Qt.py
This was undone in a recent pull request for reasons I cannot fathom.
Thanks @mnemyx for reporting, https://github.com/mottosso/Qt.py/commit/e2e4c423cca32a6d1dbcc56b7965faf142fa1182
> Repair #223

- CAVEATS.md
- Qt.py
- README.md
- examples/QtSiteConfig/QtSiteConfig.py
- examples/QtSiteConfig/README.md
- examples/QtSiteConfig/main.py
- tests.py
This pull request address the problems raised in #225 by adding backwards compatibility.
I've updated the the call to `QtSiteConfig.update_members` to attempt to call the new two argument structure, and if that fails, it logs a message and calls `update_members` passing the single argument.
> Make QtSiteConfig.update_members backwards compatible

- Dockerfile.vfxplatform2017
Adds `sed` command to Dockerfile:
```bash
sed -i -e "s~\b\(packages\b.*\)],~\1, 'pyside2uic.Compiler', 'pyside2uic.port_v' + str(sys.version_info[0])],~" setup.py
```
This makes sure that `setup.py` copies the necessary submodules of `pyside2uic` into the wheel.
Now, `pyside2-uic` exists and works in `/usr/local/pythonX.X/bin/pyside2-uic`. No symlinks were made to make it available as e.g. `pyside2-uic2.7`. If we need that, I can add it.
Dockerfile was re-built and pushed.
> Work around pyside2uic bug

- Qt.py
* Currently it does not work: I have to define my signal in my python
code instead of my ui file.
* I did not find a good solution... So for now I think it's better to
warn the user about this unsupported feature than silently tell nothing.
Do you have a solution to support this feature? :)
> --convert option: raise an error if the input ui file defined signals

- MANIFEST.in
- README.md
- setup.py
Fixes #202 
Qt.py was today added to conda/Anaconda Cloud/conda-forge and its feedstock lives [here](https://github.com/conda-forge/qt.py-feedstock/blob/master/README.md).
I added the Anaconda Cloud badge to the README and extended the install instructions with a conda example.
What's particularly cool about this, is that PySide2 can be – as of yesterday – _also_ installed with conda:
This makes me very happy:
```bash
$ conda config --add channels conda-forge
$ conda install qt.py pyside2
```
We should make our `LICENSE` be included in the [Qt.py tarball](https://pypi.org/project/Qt.py/#files) instead of keeping a copy of it in [qt.py-feedstock](https://github.com/conda-forge/qt.py-feedstock). I've added `MANIFEST.in` to this PR, which is [supposed to handle …
> Update README with conda info, include LICENSE in tarball

- Qt.py
Working on #235 
Don't merge yet. I haven't had a change to do it all yet or run the unittests yet.
> python2.6 support

- Qt.py
This adds support for the `QtX11Extras` module.  I followed the design of Qt5, and only create this module on supported platforms.  Other platforms will raise an `ImportError`.  This module has very specific and unique behavior, so I've implemented it outside of the `_misplaced_members` dictionary.  
Tested on:
pyside-1 - Windows, Linux
pyside-2 - Linux
pyqt4 - Linux
I'm happy to discuss improvements or other approaches, I just wrote this quickly for my own project, and wanted to contribute back.
> Add support for QtX11Extras

- Qt.py
Bumping because merge of #234 where [new members were added](https://github.com/mottosso/Qt.py/pull/234/files#diff-cd1d7c0a982bce680146d5b248151256).
This feels like a 1.1.0 release candidate to me! 😄
> Bump version to 1.1.0.b8

- Qt.py
- tests.py
This pull request adds support for `from Qt.QtCompat import X` so it's consistent with the other Qt modules.
> Add from Qt.QtCompat import support

- Qt.py
- examples/QtSiteConfig/QtSiteConfig.py
- examples/QtSiteConfig/main.py
- membership.py
Currently you can't use misplaced members to add new Qt modules like `Qt.QtPrintSupport` universally. It works for Qt5 because both PySide2 and PyQt5 have the QtPrintSupport module, but in Qt4, the print classes are stored on QtGui.
This patch gives `_reassign_misplaced_members` the ability to create missing modules like `Qt.QtPrintSupport`.
I modified the logic of how `_reassign_misplaced_members` rejects members a little bit from #212. If the destination method exists, but the source module was not created for Qt, it will create the module.
> Misplaced members can't create Qt sub-modules

- CAVEATS.md
- Qt.py
- tests.py
In Qt5 QPixmap.grabWidget got moved to QWidget.grab.
This code moves the member to QtCompat.
> Add Compatibility members for #151

- Qt.py
- tests.py
Workaround to [pyside-77](https://bugreports.qt.io/browse/PYSIDE-77) bug.
From the `QUiLoader` doc we should use [registerCustomWidget](https://srinikom.github.io/pyside-docs/PySide/QtUiTools/QUiLoader.html#PySide.QtUiTools.PySide.QtUiTools.QUiLoader.registerCustomWidget) method to handle custom widgets.
But on some platforms, this is causing a segfault by calling [QUiLoader.createWidget](https://srinikom.github.io/pyside-docs/PySide/QtUiTools/QUiLoader.html#PySide.QtUiTools.PySide.QtUiTools.QUiLoader.createWidget). 
So instead we fetch from customwidgets DOM node the python class objects.
Then we can directly use them in `createWidget` method.
This also fixes  #295.
> loadUi: load custom widgets with PySide(2)

- Qt.py
- README.md
- tests.py
I brought this up originally in #53 where wrapInstance() and friends were being discussed, and its cousin delete() was added in #286. It feels appropriate to add this now.
This checks the deleted state of the underlying C++ object, which is useful for Python programmers who are about to make calls on a QObject and have some reason to believe it may have been deleted out from under them.
> Add QtCompat.isValid()

- Qt.py
- README.md
Changes:
1. Adds `QtCompat.dataChanged`, a wrapper around `QAbstractItemModel.dataChanged.emit` to handle the varying arguments
2. Fixed `QtCompat.isValid` to work with PyQt5.5.11 and above
3. Adds support for `sip` when using PyQt5.5.11
> Data changed

- Qt.py
- tests.py
Adds the missing `QtGui.QMatrix` member which should be present across all Qt4/5 bindings
> Add QMatrix to QtGui members

- Qt.py
- README.md
- tests.py
I need to use PyQt5 in Maya/3ds Max/Houdini, etc. It works great until we need to install a third party script that was written expecting to be using PySide/PySide2. For the most part it works, but eventually you end up with a argument order difference or something else causing the PySide2 code to error out.
This merge request allows you to easily specify the preferred binding for each individual Qt.py import based on the full module path.
I can use the alternative workflow if we decide this isn't worth adding, but it makes the developing and testing process easier if `QtSiteConfig.preferred_binding` manages things for you.
If you need to use both PyQt and PySide in the same application you may run into problems if you just set the QT_PREFERRED_BINDING environment variable.
For example, …
> Add QtSiteConfig.preferred_binding

- Qt.py
- tests.py
Qt.py can print an error on import that looks like..
```cmd
> $ python -c "import Qt"
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
But it doesn't tell you why, and if you aren't familiar with the new `QT_PREFERRED_BINDING_JSON` variable then I expect we'll see issues pop up here.
I've changed that message to:
```cmd
> $ python -c "import Qt"
Qt.py [warning]: Failed to parse QT_PREFERRED_BINDING_JSON='blabla;bla'
Qt.py [warning]: Falling back to default preferred order
```
> Update error message for failure to parse preferred JSON

- Qt.py
We recently had an issue importing PySide2 that required a bit of debugging to ultimately figure out the cause. The failure to the user looked like `ImportError: No module named QtCore` or `'module' object has no attribute QtGui`, depending on which version of Qt.py one is running. 
The circumstances of the error are as follows:
User observes command working fine locally with PySide2 within Nuke, and sends it to the render farm.
Command fails on the render farm, running outside of Nuke, looking as if PySide2 is not available in the environment.
As it turns out, the cause of the failure is that Nuke's libraries were being picked up first in the `LD_LIBRARY_PATH` on the farm and conflicting with the external PySide2 causing an `ImportError`:
```
ImportError: /path/to/PySide2/QtCore.so: …
```
> Log warnings for unexpected ImportError of submodules instead of hiding

- Qt.py
- tests.py
This is in reference to #348.
Adds support to QtCompat.wrapInstance for classes which have a deeper inheritance hierarchy.
Calling QtCompat.wrapInstance with a pointer to an instance of class B will now return a QDialog instead of a QObject.
```python
class A(QtWidgets.QDialog):
pass
class B(A):
pass
```
> wrapInstance: Search inheritance hierarchy for a suitable class

- Qt.py
On windows, if a required dll is missing you get the exception message `DLL load failed: The specified module could not be found.`.
This makes means that you have to test each import manually so you can debug the problem.
This pull request adds the name of the module that failed to import to the warning.
Old: `Qt.py [warning]: ImportError: DLL load failed: The specified module could not be found.`
New: `Qt.py [warning]: ImportError(QtXmlPatterns): DLL load failed: The specified module could not be found.`
> Include the module name that failed to import in warning

- Qt.py
We are using a tool that vendorises Qt.py (https://github.com/krathjen/studiolibrary). But two copies of Qt.py currently write to the same location in sys.modules, meaning that they can clash with each other.
This change follows other usage of sys.modules in Qt.py and writes to the module location of the current instance of Qt.py, rather than to the global location.
> Fixed vendorised copies of Qt.py clashing

- Qt.py
If Python 2, and import error message is unicode, encode as ascii before casting to string to avoid UnicodeDecodeError.
Fix for #346 
Typical example of error message that triggers a UnicodeDecodeError:
> DLL load failed : le module spécifié est introuvable.
Typical use case where this happens:
> French Windows language and trying to use Qt.py in application with Python 2 and unicode strings.
Isolated behavior:
```python
import sys
text = str(u"DLL load failed : le module spécifié est introuvable.".encode('ascii', 'replace'))
>> b'DLL load failed : le module sp?cifi? est introuvable.'
```
> Unicode encoding in import errors - Fix for issue #346

- Qt.py
- tests.py
After much back and forth trying to pin point the issue for one of our French speaking users, I got around getting a French Windows PC and rolled back through all the changes made to fix #346 .
This resets `_setup` and `_warn_import_errors` which I thought were the original culprits. However, the issue is specific to how 3Ds Max (and other Autodesk DCCs) use unicode strings in stdout.
This change moves catching the unicode error to `_warn` and encodes the message using the preferred locale, resulting in more readable code and a more readable error message.
I updated the test to test this without the need for a full setup.
> Actual fix for #346 - unroll of #357

- Qt.py
- tests.py
In reference to issue #369: 
- Remove `assert` statement from `QtCompat.isValid()` to ensure the function is available for any objects (not just ones that inherit from `QObject`).
- Update the `test_isValid()` unittest.
> Remove assert Statement from QtCompat.isValid()

- Qt.py
In this pull request, I update the logic in `translate()` to allow optional arguments.
I decided to open this pull request after I ran into a ui file compilation difference:
```
pyside2-uic foo.ui --> QCoreApplication.translate("MainWindow", u"MainWindow", None) (pyside-5.15.4)
pyside2-uic foo.ui --> QCoreApplication.translate("MainWindow", u"MainWindow", None, -1) (pyside-5.12.6)
```
Notice how the first compilation with `pyside-5.15.4` returns translate with 3 arguments instead of 4.
When we eventually use `QtCompat.translate()` we run into the following error:
```
File "/dd/shows/DEV01/user/work.akelada/tools/cent7_64/package/launchpad/0.1.2/python/launchpad/Ui_launchpad_UI.py", line 205, in retranslateUi
MainWindow.setWindowTitle(QtCompat.translate("MainWindow", u"MainWindow", None)) …
```
> fix translate arguments

- Qt.py
- tests.py
https://github.com/mottosso/Qt.py/issues/401
This is an attempt to have the least amount of impact on the existing functionality, and allow Python custom widgets paths to work.   
The original `header` authored by the user will always be attempted first.  If it fails to import for the PySide implementation, a second attempt is made using the original Qt.py `headerToModule` function.
> Updating the `headerToModule` def to only manipulate '.h' files.

- Qt.py
Long time listener, first time caller from [The Third Floor](https://thethirdfloorinc.com/)
I located these 4 members in PySide6 and based this modification on similar commits. Please let me know if there's a better way to do this. We're actively testing in PySide6 and PySide2, so I may discover more misplaced members.
> Updated _misplaced_members for PySide6

- Qt.py
QtCore.QSortFilterProxyModel was removed from `_misplaced_members['PyQt5']` in the latest release.
> Add QtCore.QSortFilterProxyModel to PyQt5 in _misplaced_members

- README.md
Just a little fix on the readme documentation :)
| `QtCore.Qt.MidButton`  | `QtCompat.QtCore.Qt.MidButton` >> | `QtCore.Qt.MidButton`  | `QtCompat.Qt.MidButton`
> little fix QT 6 Transition documentation

- .github/workflows/pyside6.yml
- CAVEATS.md
- Qt.py
- Qt_convert_enum.py
- README.md
- examples/QtSiteConfig/QtSiteConfig.py
- run_tests.py
- setup.py
- tests.py
Add the binding information for PyQt6 support.
PyQt6 seems to have removed a lot of backwards compatible support that PySide6 has not. This introduces a few issues that should be figured out before this is merged. I will add additional notes calling out the specifics.
> Add PyQt6 support

- Qt.py
- README.md
Addresses #410.
This maintains the PySide2 location for these widgets, `QtSvg`. In Qt6 they have been moved into their own `QtSvgWidgets` module.
This Pull Request is intended to be merged after #431 which is why it contains so many code changes at the moment.
View the actual changes https://github.com/blurstudio-forks/Qt.py/compare/mikeh/pyqt6...blurstudio-forks:Qt.py:mikeh/svg_restore
> Restore QGraphicsSvgItem and QSvgWidget to QtSvg

- CAVEATS.md
- Qt_convert_enum.py
- setup.cfg
- tests.py
These have a high chance of false positives so this does not actually make the changes, simply output the places to look for changes.
This also improves the code fold ability of multi-line strings in test.py.
> Qt_convert_enum can now find potential enum issues
